### ISSUE TITLE
GLDAS build fails on Orion

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/GLDAS#18]
The latest version of the global workflow develop fails during the gldas build step on Orion (I do not know when this problem first occurred as this is the first time I attempted to build on Orion).  It is the first executable, gdas2gldas, that fails when sourcing gldas.fd/modulefiles/gdas2gldas.orion because the following modules are not found:
``` 
netcdfp/4.7.4.release
esmflocal/8_0_0.release
```

These modules are located under:
```
/apps/contrib/NCEPLIBS/lib/modulefiles.  
```
But the MOD_PATH from gldas.fd/sorc/machine-setup.sh is:
```
/apps/contrib/NCEPLIBS/orion/modulefiles
```
If I add this line to my copy of gdas2gldas.orion:
```
module use -a /apps/contrib/NCEPLIBS/lib/modulefiles
```
the build of all gldas executables completes without failure.  In speaking with @KateFriedman-NOAA, she has the preceding line in her .bashrc, allowing her to find the modules, whereas I do not have this line in my .bashrc.   I recommend that this "module use" statement to be included in the gldas modulefiles rather than relying on our .bashrc files.

**Comment by CatherineThomas-NOAA** [comment]
Starting with a clean checkout, I found that I also needed to add the same module use line:
```
module use -a /apps/contrib/NCEPLIBS/lib/modulefiles
```
to the gldas2gdas.orion modulefile as well.

**Comment by KateFriedman-NOAA** [comment]
This work has been completed, closing issue, thanks!
