### ISSUE TITLE
Inconsistent ESMF version

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/GLDAS#45]
The ESMF version for GLDAS is currently set to 8_0_1.  It seems that this may be a mistake, however.  When the module files were recently updated to revert the compiler versions from 2022.2 to 18.0.4, the ESMF version was changed from 8_2_0 to 8_0_1.  However, before the compilers were set to 2022.2, the ESMF version was 8_1_1.  Is 8_0_1 really the correct version, or should it be incremented to 8_1_1 or 8_2_0?

**Comment by DavidHuber-NOAA** [comment]
See commit history from [9415a7b](https://github.com/NOAA-EMC/GLDAS/commit/9415a7bce26f3615ac6a08b228387e0f183f8b19#) and [fd8ba62](https://github.com/NOAA-EMC/GLDAS/commit/fd8ba62275bb27b0beecbc7c6985c1d61537f299) @HelinWei-NOAA @KateFriedman-NOAA.

**Comment by DavidHuber-NOAA** [comment]
@HelinWei-NOAA Should the ESMF library and Intel compiler versions be re-upgraded?  I'm happy to make the module changes for Orion and Hera and give them a test run.

**Comment by HelinWei-NOAA** [comment]
@DavidHuber-NOAA Sure. Please create a PT to merge your changes. Thanks.
